name: Check Then Release

on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  generate-statistics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      py
